/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.bsi.biblioteca;

import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class AlunoForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AlunoForm.class.getName());

    /**
     * Creates new form FuncionarioForm
     */
    public AlunoForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        btnFazerReserva = new javax.swing.JButton();
        btnReserva = new javax.swing.JButton();
        btnSeusEmprestimos = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(900, 500));

        panelHeader.setPreferredSize(new java.awt.Dimension(100, 80));
        panelHeader.setLayout(new java.awt.GridLayout(2, 1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Biblioteca BSI");
        panelHeader.add(jLabel2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Área do Aluno");
        panelHeader.add(jLabel1);

        getContentPane().add(panelHeader, java.awt.BorderLayout.PAGE_START);

        panelMenu.setBackground(new java.awt.Color(44, 62, 80));
        panelMenu.setPreferredSize(new java.awt.Dimension(300, 150));
        panelMenu.setLayout(new javax.swing.BoxLayout(panelMenu, javax.swing.BoxLayout.Y_AXIS));

        btnFazerReserva.setBackground(new java.awt.Color(52, 73, 94));
        btnFazerReserva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFazerReserva.setForeground(new java.awt.Color(255, 255, 255));
        btnFazerReserva.setText("Fazer Reserva");
        btnFazerReserva.setAlignmentX(0.5F);
        btnFazerReserva.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15));
        btnFazerReserva.setFocusPainted(false);
        btnFazerReserva.setMaximumSize(new java.awt.Dimension(200, 25));
        btnFazerReserva.addActionListener(this::btnFazerReservaActionPerformed);
        panelMenu.add(btnFazerReserva);

        btnReserva.setBackground(new java.awt.Color(52, 73, 94));
        btnReserva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReserva.setForeground(new java.awt.Color(255, 255, 255));
        btnReserva.setText("Suas Reservas");
        btnReserva.setAlignmentX(0.5F);
        btnReserva.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15));
        btnReserva.setFocusPainted(false);
        btnReserva.setMaximumSize(new java.awt.Dimension(200, 25));
        btnReserva.addActionListener(this::btnReservaActionPerformed);
        panelMenu.add(btnReserva);

        btnSeusEmprestimos.setBackground(new java.awt.Color(52, 73, 94));
        btnSeusEmprestimos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSeusEmprestimos.setForeground(new java.awt.Color(255, 255, 255));
        btnSeusEmprestimos.setText("Seus Empréstimos");
        btnSeusEmprestimos.setAlignmentX(0.5F);
        btnSeusEmprestimos.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15));
        btnSeusEmprestimos.setFocusPainted(false);
        btnSeusEmprestimos.setMaximumSize(new java.awt.Dimension(200, 25));
        btnSeusEmprestimos.addActionListener(this::btnSeusEmprestimosActionPerformed);
        panelMenu.add(btnSeusEmprestimos);

        getContentPane().add(panelMenu, java.awt.BorderLayout.LINE_START);

        btnSair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 0, 0));
        btnSair.setText("Sair");
        btnSair.addActionListener(this::btnSairActionPerformed);
        getContentPane().add(btnSair, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(filler1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
         JOptionPane.showMessageDialog(
                null,
                "Obrigado por usar este sistema!",
                "Mensagem",
                JOptionPane.INFORMATION_MESSAGE
        );
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnFazerReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFazerReservaActionPerformed
         FazerReservaForm telaConsultaAcervo = new FazerReservaForm();
        telaConsultaAcervo.setVisible(true);
    }//GEN-LAST:event_btnFazerReservaActionPerformed

    private void btnReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservaActionPerformed
        ConsultaReservaForm telaConsultaReserva = new ConsultaReservaForm();
        telaConsultaReserva.setVisible(true);
    }//GEN-LAST:event_btnReservaActionPerformed

    private void btnSeusEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeusEmprestimosActionPerformed
       ConsultaEmprestimos telaConsultaEmprestimos = new ConsultaEmprestimos();
        telaConsultaEmprestimos.setVisible(true);
    }//GEN-LAST:event_btnSeusEmprestimosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AlunoForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFazerReserva;
    private javax.swing.JButton btnReserva;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSeusEmprestimos;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
