/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.bsi.biblioteca;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos
 */
public class AutoresForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AutoresForm.class.getName());

    /**
     * Creates new form Autores
     */
    public AutoresForm() {
        initComponents();
        btnIncluir.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        carregarAutores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdAutor = new javax.swing.JTextField();
        txtNomeAutor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jscrollAutores = new javax.swing.JScrollPane();
        tblAutores = new javax.swing.JTable();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        brnVolta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Biblioteca BSI");

        jLabel2.setText("Cadastro de Autores");

        jLabel3.setText("Id:");

        txtIdAutor.setEditable(false);
        txtIdAutor.setColumns(5);
        txtIdAutor.setText(" ");
        txtIdAutor.addActionListener(this::txtIdAutorActionPerformed);

        txtNomeAutor.setColumns(30);
        txtNomeAutor.setText(" ");

        jLabel4.setText("Nome: ");

        tblAutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "nome"
            }
        ));
        tblAutores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAutoresmouseCliked(evt);
            }
        });
        jscrollAutores.setViewportView(tblAutores);

        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(this::btnIncluirActionPerformed);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(this::btnAlterarActionPerformed);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        brnVolta.setText("Volta");
        brnVolta.addActionListener(this::brnVoltaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnIncluir)
                                    .addComponent(jLabel4))
                                .addGap(4, 4, 4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btnAlterar)
                                .addGap(27, 27, 27)
                                .addComponent(btnExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jscrollAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(brnVolta)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jscrollAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(brnVolta)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdAutorActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        if (!validarCamposObrigatorios()) {
            return;
        }
        try {
            Connection conn = Conexao.getConnection();

            String sql
                    = "INSERT INTO autor ( nome) "
                    + "VALUES (?)";

            PreparedStatement ps = conn.prepareStatement(sql);

            // Status vindo do ButtonGroup
            String status = "";

            ps.setString(1, txtNomeAutor.getText());

            ps.executeUpdate();

            ps.close();
            conn.close();

            JOptionPane.showMessageDialog(this,
                    "Autor incluído com sucesso!!!");
            limparTela();
            carregarAutores();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao incluir: " + e.getMessage());
        }
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparTela();
        btnIncluir.setEnabled(true);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void tbAutoresmouseCliked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAutoresmouseCliked
        // Se quiser exigir duplo clique, descomente:
        // if (evt.getClickCount() != 2) return;
        int linha = tblAutores.getSelectedRow();

        if (linha == -1) {
            return;
        }

        // Recupera dados da JTable
        txtIdAutor.setText(tblAutores.getValueAt(linha, 0).toString());
        txtNomeAutor.setText(tblAutores.getValueAt(linha, 1).toString());

         // Habilita botões
        btnIncluir.setEnabled(false);
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);
    }//GEN-LAST:event_tbAutoresmouseCliked

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (txtIdAutor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Selecione um Autor na lista para alterar.");
            return;
        }
        if (!validarCamposObrigatorios()) {
            return;
        }
        try {
            Connection conn = Conexao.getConnection();

            String sql
                    = "UPDATE autor "
                    + "SET nome = ? "
                    + "WHERE id = ?";

            PreparedStatement ps = conn.prepareStatement(sql);

            ps.setString(1, txtNomeAutor.getText());
             ps.setInt(2, Integer.parseInt(txtIdAutor.getText()));
            ps.executeUpdate();

            ps.close();
            conn.close();

            // 3️⃣ Feedback ao usuário
            JOptionPane.showMessageDialog(this,
                    "Autor alterado com sucesso!");

            // 4️⃣ Limpa e recarrega
            limparTela();
            carregarAutores();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao alterar Autor: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int idSelecionado = Integer.parseInt(txtIdAutor.getText());

        

        // Desabilita botões durante a confirmação
        btnIncluir.setEnabled(false);
        btnAlterar.setEnabled(false);

        int opcao = JOptionPane.showConfirmDialog(
                this,
                "Confirma a exclusão do Autor selecionado?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        // Se cancelar
        if (opcao != JOptionPane.YES_OPTION) {
            btnIncluir.setEnabled(true);
            btnAlterar.setEnabled(true);
            return;
        }

        try {
            Connection conn = Conexao.getConnection();

            String sql = "DELETE FROM autor WHERE id = ?";

            PreparedStatement ps = conn.prepareStatement(sql);

            ps.setInt(1, Integer.parseInt(txtIdAutor.getText()));

            ps.executeUpdate();

            ps.close();
            conn.close();

            JOptionPane.showMessageDialog(this,
                    "Autor excluído com sucesso!");

            // Volta para tela inicial
            limparTela();
            carregarAutores();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao excluir Autor: " + e.getMessage());
        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void brnVoltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnVoltaActionPerformed
        FuncionarioForm telaFuncionrio = new FuncionarioForm();
        telaFuncionrio.setVisible(true);
    }//GEN-LAST:event_brnVoltaActionPerformed
    private boolean validarCamposObrigatorios() {

        // Nome
        if (txtNomeAutor.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Informe o nome do Autor!");
            txtNomeAutor.requestFocus();
            return false;
        }

        return true; // tudo OK
    }

    private void limparTela() {

        // Campos de texto
        if (txtIdAutor != null) {
            txtIdAutor.setText("");
        }
        if (txtNomeAutor != null) {
            txtNomeAutor.setText("");
        }

        btnIncluir.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }

    private void carregarAutores() {

        DefaultTableModel model
                = (DefaultTableModel) tblAutores.getModel();

        model.setRowCount(0); // limpa a tabela

        try {
            Connection conn = Conexao.getConnection();

            String sql
                    = "SELECT  id, nome "
                    + "FROM autor "
                    + "ORDER BY nome ASC";

            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id"),
                    rs.getString("nome")
                });
            }

            rs.close();
            ps.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao carregar Autores: " + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnVolta;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jscrollAutores;
    private javax.swing.JTable tblAutores;
    private javax.swing.JTextField txtIdAutor;
    private javax.swing.JTextField txtNomeAutor;
    // End of variables declaration//GEN-END:variables
}
