/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.bsi.biblioteca;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import javax.swing.JTable;
import javax.swing.JLabel;

import javax.swing.table.TableColumn;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Carlos
 */
public class ConsultaEmprestimos extends javax.swing.JFrame {

    private int idAluno;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultaEmprestimos.class.getName());

    /**
     * Creates new form ConsultaEmprestimos
     */
    public ConsultaEmprestimos() {
        initComponents();
        idAluno = SessaoUsuario.idUsuarioLogado;
        carregarEmprestimo();
        ajustarLarguraColunas();
        ocultarColunaId();
    }

    private void ajustarLarguraColunas() {

        // Impede redimensionamento automático
        tblEmprestimos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        // Coluna 0 → ID (vai ser ocultada depois)
        tblEmprestimos.getColumnModel().getColumn(0).setPreferredWidth(0);

        // Coluna 1 → Título
        tblEmprestimos.getColumnModel().getColumn(1).setPreferredWidth(250);

        // Coluna 2 → Autores
        tblEmprestimos.getColumnModel().getColumn(2).setPreferredWidth(220);

        // Coluna 3 → Data Empréstimo
        tblEmprestimos.getColumnModel().getColumn(3).setPreferredWidth(110);

        // Coluna 4 → Data Prevista
        tblEmprestimos.getColumnModel().getColumn(4).setPreferredWidth(130);

        // Coluna 5 → Status
        tblEmprestimos.getColumnModel().getColumn(5).setPreferredWidth(170);

        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
        center.setHorizontalAlignment(JLabel.CENTER);

        tblEmprestimos.getColumnModel().getColumn(3).setCellRenderer(center);
        tblEmprestimos.getColumnModel().getColumn(4).setCellRenderer(center);

    }

    private void ocultarColunaId() {
        TableColumn colunaId = tblEmprestimos.getColumnModel().getColumn(0);

        colunaId.setMinWidth(0);
        colunaId.setMaxWidth(0);
        colunaId.setPreferredWidth(0);
    }

    private void carregarEmprestimo() {
        DefaultTableModel model = (DefaultTableModel) tblEmprestimos.getModel();
        model.setRowCount(0); // limpa a tabela

        String sql = "SELECT e.id AS emprestimo_id, "
                + "       t.titulo, "
                + "       GROUP_CONCAT(au.nome SEPARATOR ', ') AS autores, "
                + "       e.data_emprestimo, "
                + "       e.data_prevista_devolucao, "
                + "       e.status_emprestimo "
                + "FROM emprestimo e "
                + "INNER JOIN acervo a ON e.acervo_id = a.id "
                + "INNER JOIN titulo t ON a.titulo_id = t.id "
                + "INNER JOIN titulo_autor ta ON t.id = ta.titulo_id "
                + "INNER JOIN autor au ON ta.autor_id = au.id "
                + "WHERE e.usuario_id = ? "
                + "GROUP BY e.id, t.titulo, e.data_emprestimo, "
                + "         e.data_prevista_devolucao, e.status_emprestimo";

        try (Connection conn = Conexao.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setInt(1, idAluno);

            try (ResultSet rs = ps.executeQuery()) {
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getString("emprestimo_id"),
                        rs.getString("titulo"),
                        rs.getString("autores"),
                        sdf.format(rs.getTimestamp("data_emprestimo")),
                        sdf.format(rs.getTimestamp("data_prevista_devolucao")),
                        rs.getString("status_emprestimo")

                    });
                }

            }

            //ajustarLarguraColunas();
            //ocultarColunaIdReserva();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao carregar Emprestimos: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmprestimos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Biblioteca BSI");

        jLabel2.setText("Área do ALuno");

        jLabel3.setText("Consultar  Empréstimos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Seus Empréstimos"));

        tblEmprestimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Empréstimo", "Título", "Autor", "Data do Empréstimo", "Data Prevista Devolução", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblEmprestimos);

        jButton1.setText("Volta");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(303, 303, 303))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(435, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(343, 343, 343)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(300, 300, 300))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Fecha a janela atual
        this.dispose();
        AlunoForm telaAluno = new AlunoForm();
        telaAluno.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsultaEmprestimos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmprestimos;
    // End of variables declaration//GEN-END:variables
}
