/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.bsi.biblioteca;

/**
 *
 * @author Carlos
 */
public class DashboardView1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardView1.class.getName());

    /**
     * Creates new form DashboardView
     */
    public DashboardView1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelCard1 = new javax.swing.JPanel();
        lblCard11 = new javax.swing.JLabel();
        lblCard12 = new javax.swing.JLabel();
        lblCard13 = new javax.swing.JLabel();
        panelCard2 = new javax.swing.JPanel();
        lblCard21 = new javax.swing.JLabel();
        lblCard22 = new javax.swing.JLabel();
        lblCard23 = new javax.swing.JLabel();
        panelCard3 = new javax.swing.JPanel();
        lblCard31 = new javax.swing.JLabel();
        lblCard32 = new javax.swing.JLabel();
        lblCard33 = new javax.swing.JLabel();
        panelCard4 = new javax.swing.JPanel();
        lblCard41 = new javax.swing.JLabel();
        lblCard42 = new javax.swing.JLabel();
        lblCard43 = new javax.swing.JLabel();
        panelGrafico = new javax.swing.JPanel();
        panelPizza = new javax.swing.JPanel();
        jblVerde = new javax.swing.JLabel();
        jblAndamento = new javax.swing.JLabel();
        jblLaraja = new javax.swing.JLabel();
        jblAtraso = new javax.swing.JLabel();
        jblAzul = new javax.swing.JLabel();
        jblFinalizado = new javax.swing.JLabel();
        panelAlertas = new javax.swing.JPanel();
        panelAlerta1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jblAlertaCritico = new javax.swing.JLabel();
        jblAndamento1 = new javax.swing.JLabel();
        panelAlerta2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jblAlertaCritico1 = new javax.swing.JLabel();
        jblAndamento2 = new javax.swing.JLabel();
        panelAlerta3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jblAlertaCritico2 = new javax.swing.JLabel();
        jblAndamento3 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Biblioteca");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(900, 900));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema Biblioteca");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Dashboard");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        panelCard1.setBackground(new java.awt.Color(153, 153, 255));
        panelCard1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panelCard1.setPreferredSize(new java.awt.Dimension(850, 102));

        lblCard11.setText("ICON");

        lblCard12.setText("Total de Títulos Catalogados");

        lblCard13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCard13.setText("0");

        javax.swing.GroupLayout panelCard1Layout = new javax.swing.GroupLayout(panelCard1);
        panelCard1.setLayout(panelCard1Layout);
        panelCard1Layout.setHorizontalGroup(
            panelCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCard1Layout.createSequentialGroup()
                .addGroup(panelCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCard1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panelCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCard12)
                            .addComponent(lblCard11)))
                    .addGroup(panelCard1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lblCard13)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        panelCard1Layout.setVerticalGroup(
            panelCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCard1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCard11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCard12)
                .addGap(18, 18, 18)
                .addComponent(lblCard13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 180, -1));

        panelCard2.setBackground(new java.awt.Color(153, 153, 255));
        panelCard2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panelCard2.setPreferredSize(new java.awt.Dimension(850, 102));

        lblCard21.setText("ICON");

        lblCard22.setText("Total de Títulos Catalogados");

        lblCard23.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCard23.setText("0");

        javax.swing.GroupLayout panelCard2Layout = new javax.swing.GroupLayout(panelCard2);
        panelCard2.setLayout(panelCard2Layout);
        panelCard2Layout.setHorizontalGroup(
            panelCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCard2Layout.createSequentialGroup()
                .addGroup(panelCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCard2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panelCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCard22)
                            .addComponent(lblCard21)))
                    .addGroup(panelCard2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lblCard23)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        panelCard2Layout.setVerticalGroup(
            panelCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCard2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCard21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCard22)
                .addGap(18, 18, 18)
                .addComponent(lblCard23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 180, -1));

        panelCard3.setBackground(new java.awt.Color(153, 153, 255));
        panelCard3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panelCard3.setPreferredSize(new java.awt.Dimension(850, 102));

        lblCard31.setText("ICON");

        lblCard32.setText("Total de Títulos Catalogados");

        lblCard33.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCard33.setText("0");

        javax.swing.GroupLayout panelCard3Layout = new javax.swing.GroupLayout(panelCard3);
        panelCard3.setLayout(panelCard3Layout);
        panelCard3Layout.setHorizontalGroup(
            panelCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCard3Layout.createSequentialGroup()
                .addGroup(panelCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCard3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblCard31))
                    .addGroup(panelCard3Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lblCard33)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCard3Layout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addComponent(lblCard32))
        );
        panelCard3Layout.setVerticalGroup(
            panelCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCard3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCard31)
                .addGap(18, 18, 18)
                .addComponent(lblCard32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCard33)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelCard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 180, -1));

        panelCard4.setBackground(new java.awt.Color(153, 153, 255));
        panelCard4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panelCard4.setPreferredSize(new java.awt.Dimension(850, 102));

        lblCard41.setText("ICON");

        lblCard42.setText("Total de Títulos Catalogados");

        lblCard43.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCard43.setText("0");

        javax.swing.GroupLayout panelCard4Layout = new javax.swing.GroupLayout(panelCard4);
        panelCard4.setLayout(panelCard4Layout);
        panelCard4Layout.setHorizontalGroup(
            panelCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCard4Layout.createSequentialGroup()
                .addGroup(panelCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCard4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panelCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCard42)
                            .addComponent(lblCard41)))
                    .addGroup(panelCard4Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lblCard43)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        panelCard4Layout.setVerticalGroup(
            panelCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCard4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCard41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCard42)
                .addGap(18, 18, 18)
                .addComponent(lblCard43)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelCard4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 180, -1));

        panelGrafico.setBackground(new java.awt.Color(204, 255, 204));
        panelGrafico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Situação de Empréstimos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 255))); // NOI18N

        panelPizza.setBackground(new java.awt.Color(255, 255, 255));
        panelPizza.setLayout(new java.awt.BorderLayout());

        jblVerde.setBackground(new java.awt.Color(0, 153, 0));
        jblVerde.setOpaque(true);

        jblAndamento.setText("Em Andamento");

        jblLaraja.setBackground(new java.awt.Color(255, 102, 0));
        jblLaraja.setOpaque(true);

        jblAtraso.setText("Em Atraso");

        jblAzul.setBackground(new java.awt.Color(0, 0, 255));
        jblAzul.setOpaque(true);

        jblFinalizado.setText("Finalizados");

        javax.swing.GroupLayout panelGraficoLayout = new javax.swing.GroupLayout(panelGrafico);
        panelGrafico.setLayout(panelGraficoLayout);
        panelGraficoLayout.setHorizontalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGraficoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(panelGraficoLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jblVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jblAndamento)
                .addGap(96, 96, 96)
                .addComponent(jblLaraja, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jblAtraso)
                .addGap(72, 72, 72)
                .addComponent(jblAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jblFinalizado)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        panelGraficoLayout.setVerticalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGraficoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(panelPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addGroup(panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblAtraso, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jblFinalizado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jblAndamento)
                        .addComponent(jblVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGraficoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblAzul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblLaraja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(panelGrafico, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 670, 260));

        panelAlertas.setBackground(new java.awt.Color(204, 255, 204));
        panelAlertas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alertas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 51, 255))); // NOI18N

        panelAlerta1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Itens não Devolvidos");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setText("0");

        jblAlertaCritico.setBackground(new java.awt.Color(255, 0, 0));
        jblAlertaCritico.setOpaque(true);

        jblAndamento1.setText("Crítico");

        javax.swing.GroupLayout panelAlerta1Layout = new javax.swing.GroupLayout(panelAlerta1);
        panelAlerta1.setLayout(panelAlerta1Layout);
        panelAlerta1Layout.setHorizontalGroup(
            panelAlerta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlerta1Layout.createSequentialGroup()
                .addGroup(panelAlerta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlerta1Layout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addComponent(jLabel15))
                    .addGroup(panelAlerta1Layout.createSequentialGroup()
                        .addGroup(panelAlerta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAlerta1Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAlerta1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jblAlertaCritico, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jblAndamento1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelAlerta1Layout.setVerticalGroup(
            panelAlerta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlerta1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAlerta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblAlertaCritico, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblAndamento1))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        panelAlerta2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Itens não Devolvidos");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setText("0");

        jblAlertaCritico1.setBackground(new java.awt.Color(255, 255, 0));
        jblAlertaCritico1.setOpaque(true);

        jblAndamento2.setText("Atenção");

        javax.swing.GroupLayout panelAlerta2Layout = new javax.swing.GroupLayout(panelAlerta2);
        panelAlerta2.setLayout(panelAlerta2Layout);
        panelAlerta2Layout.setHorizontalGroup(
            panelAlerta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlerta2Layout.createSequentialGroup()
                .addGroup(panelAlerta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlerta2Layout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addComponent(jLabel17))
                    .addGroup(panelAlerta2Layout.createSequentialGroup()
                        .addGroup(panelAlerta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAlerta2Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAlerta2Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jblAlertaCritico1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jblAndamento2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelAlerta2Layout.setVerticalGroup(
            panelAlerta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlerta2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAlerta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblAlertaCritico1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblAndamento2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAlerta3.setBackground(new java.awt.Color(51, 153, 255));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Aguardando Empréstimo");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setText("0");

        jblAlertaCritico2.setBackground(new java.awt.Color(255, 0, 0));
        jblAlertaCritico2.setOpaque(true);

        jblAndamento3.setText("Crítico");

        javax.swing.GroupLayout panelAlerta3Layout = new javax.swing.GroupLayout(panelAlerta3);
        panelAlerta3.setLayout(panelAlerta3Layout);
        panelAlerta3Layout.setHorizontalGroup(
            panelAlerta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlerta3Layout.createSequentialGroup()
                .addGroup(panelAlerta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlerta3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19))
                    .addGroup(panelAlerta3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jblAlertaCritico2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelAlerta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblAndamento3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelAlerta3Layout.setVerticalGroup(
            panelAlerta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlerta3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(12, 12, 12)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAlerta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblAlertaCritico2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblAndamento3))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelAlertasLayout = new javax.swing.GroupLayout(panelAlertas);
        panelAlertas.setLayout(panelAlertasLayout);
        panelAlertasLayout.setHorizontalGroup(
            panelAlertasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlertasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panelAlerta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(panelAlerta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(panelAlerta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        panelAlertasLayout.setVerticalGroup(
            panelAlertasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlertasLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelAlertasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelAlerta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAlerta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAlerta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        getContentPane().add(panelAlertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 550, 750, 250));

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 830, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
         this.dispose();
        RelatorioForm telaRelatorio = new RelatorioForm();
        telaRelatorio.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardView1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jblAlertaCritico;
    private javax.swing.JLabel jblAlertaCritico1;
    private javax.swing.JLabel jblAlertaCritico2;
    private javax.swing.JLabel jblAndamento;
    private javax.swing.JLabel jblAndamento1;
    private javax.swing.JLabel jblAndamento2;
    private javax.swing.JLabel jblAndamento3;
    private javax.swing.JLabel jblAtraso;
    private javax.swing.JLabel jblAzul;
    private javax.swing.JLabel jblFinalizado;
    private javax.swing.JLabel jblLaraja;
    private javax.swing.JLabel jblVerde;
    private javax.swing.JLabel lblCard11;
    private javax.swing.JLabel lblCard12;
    private javax.swing.JLabel lblCard13;
    private javax.swing.JLabel lblCard21;
    private javax.swing.JLabel lblCard22;
    private javax.swing.JLabel lblCard23;
    private javax.swing.JLabel lblCard31;
    private javax.swing.JLabel lblCard32;
    private javax.swing.JLabel lblCard33;
    private javax.swing.JLabel lblCard41;
    private javax.swing.JLabel lblCard42;
    private javax.swing.JLabel lblCard43;
    private javax.swing.JPanel panelAlerta1;
    private javax.swing.JPanel panelAlerta2;
    private javax.swing.JPanel panelAlerta3;
    private javax.swing.JPanel panelAlertas;
    private javax.swing.JPanel panelCard1;
    private javax.swing.JPanel panelCard2;
    private javax.swing.JPanel panelCard3;
    private javax.swing.JPanel panelCard4;
    private javax.swing.JPanel panelGrafico;
    private javax.swing.JPanel panelPizza;
    // End of variables declaration//GEN-END:variables
}
