/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.bsi.biblioteca;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

import java.sql.SQLException;
import java.time.LocalDate;

import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;

/**
 *
 * @author Carlos
 */
public class DevolucaoFrame extends javax.swing.JFrame {

    private int idAluno;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DevolucaoFrame.class.getName());

    /**
     * Creates new form DevolucaoFrame
     */
    public DevolucaoFrame() {
        initComponents();
        inicializaCursor();

    }

    private void inicializaCursor() {
        // Garante foco e seleção após a tela estar visível
        SwingUtilities.invokeLater(() -> {
            txtIdAluno.requestFocusInWindow();
            txtIdAluno.selectAll();
            btnEfetivaDevolucao.setVisible(false);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdAluno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        btnEfetivaDevolucao = new javax.swing.JButton();
        txtIdEmprestimo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDataEmprestimo = new javax.swing.JTextField();
        labelDatadevolucao = new javax.swing.JLabel();
        txtDataDevolucaoPrevista = new javax.swing.JTextField();
        txtIdAcervo = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblEmprestimos = new javax.swing.JTable();
        btnVolta = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Biblioteca");

        jLabel2.setText("Devolução de Livros");

        jLabel3.setText("Id do Aluno:");

        txtIdAluno.setColumns(5);
        txtIdAluno.setText(" Informe ID e tecle ENTER");
        txtIdAluno.addActionListener(this::txtIdAlunoidAlunoPerformed);

        jLabel4.setText("Título:");

        txtTitulo.setEditable(false);
        txtTitulo.setColumns(30);
        txtTitulo.setText(" ");

        btnEfetivaDevolucao.setText("Efetivar Devolução");
        btnEfetivaDevolucao.addActionListener(this::btnEfetivaDevolucaoActionPerformed);

        txtIdEmprestimo.setEditable(false);
        txtIdEmprestimo.setColumns(10);
        txtIdEmprestimo.setText(" ");

        jLabel5.setText("Data do Empréstimo: ");

        txtDataEmprestimo.setEditable(false);
        txtDataEmprestimo.setColumns(10);

        labelDatadevolucao.setText("Data Previsão Devolução: ");

        txtDataDevolucaoPrevista.setEditable(false);
        txtDataDevolucaoPrevista.setColumns(15);

        txtIdAcervo.setEditable(false);
        txtIdAcervo.setColumns(5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(txtIdEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(txtIdAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(labelDatadevolucao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataDevolucaoPrevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(218, 218, 218))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEfetivaDevolucao)
                        .addGap(334, 334, 334))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDatadevolucao)
                    .addComponent(txtDataDevolucaoPrevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(btnEfetivaDevolucao)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        tblEmprestimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Empréstimo", "Titulo", "Data do Empréstimo", "Data Prevista Devolução", "Situação", "ID Acervo"
            }
        ));
        tblEmprestimos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDevolucaoMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblEmprestimos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jScrollPane5.setViewportView(jPanel3);

        btnVolta.setText("Volta");
        btnVolta.addActionListener(this::btnVoltaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnVolta)
                .addGap(356, 356, 356))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVolta)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdAlunoidAlunoPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdAlunoidAlunoPerformed

        String texto = txtIdAluno.getText().trim();

        // Verifica se está vazio
        if (texto.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Informe o ID do aluno.",
                    "Atenção",
                    JOptionPane.WARNING_MESSAGE);
            txtIdAluno.requestFocusInWindow();
            txtIdAluno.selectAll();
            return;
        }

        // Verifica se é numérico
        if (!texto.matches("\\d+")) {
            JOptionPane.showMessageDialog(this,
                    "O ID deve conter apenas números.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
            txtIdAluno.requestFocusInWindow();
            txtIdAluno.selectAll();
            return;
        }

        // Se chegou aqui, é numérico
        idAluno = Integer.parseInt(texto);

        // 👉 Próxima ação
        carregarEmprestimos();


    }//GEN-LAST:event_txtIdAlunoidAlunoPerformed

    private void btnEfetivaDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfetivaDevolucaoActionPerformed

        String tituloLivro = txtTitulo.getText();

        atualizarrEmprestimo();
        //@AQUI
        String textoId = txtIdAcervo.getText().trim();
        int idAcervo = Integer.parseInt(textoId);
        atualizarAcervo(idAcervo);
        // Se chegou aqui, é numérico

        String mensagem = String.format(
                "Título \"%s\" Devolvido com sucesso.",
                tituloLivro
        );

        JOptionPane.showMessageDialog(
                this,
                mensagem,
                "Empréstimo realizado",
                JOptionPane.INFORMATION_MESSAGE
        );
        carregarEmprestimos();
        limparSelecao();
    }//GEN-LAST:event_btnEfetivaDevolucaoActionPerformed

    private void btnVoltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltaActionPerformed
        // Fecha a janela atual
        this.dispose();
        FuncionarioForm telaFuncionrio = new FuncionarioForm();
        telaFuncionrio.setVisible(true);
    }//GEN-LAST:event_btnVoltaActionPerformed

    private void tblDevolucaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDevolucaoMouseClicked
        // Se quiser exigir duplo clique, descomente:
        // if (evt.getClickCount() != 2) return;
        int linha = tblEmprestimos.getSelectedRow();

        if (linha == -1) {
            return;
        }

        // Recupera dados da JTable
        txtIdEmprestimo.setText(tblEmprestimos.getValueAt(linha, 0).toString());
        txtTitulo.setText(tblEmprestimos.getValueAt(linha, 1).toString());
        txtDataEmprestimo.setText(tblEmprestimos.getValueAt(linha, 2).toString());
        txtDataDevolucaoPrevista.setText(tblEmprestimos.getValueAt(linha, 3).toString());
        txtIdAcervo.setText(tblEmprestimos.getValueAt(linha, 5).toString());

        // Habilita botões
        txtIdAluno.setEnabled(false);
        btnEfetivaDevolucao.setVisible(true);


    }//GEN-LAST:event_tblDevolucaoMouseClicked
    private void atualizarrEmprestimo() {
        String idReservaTexto = txtIdEmprestimo.getText().trim();

        // Converte para int
        int idEmprestimo;
        try {
            idEmprestimo = Integer.parseInt(idReservaTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "ID da reserva inválido.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        String dataPrevistaTexto = txtDataDevolucaoPrevista.getText().trim(); // pega a data prevista
        // Define o formato da data da tela
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        // Converte a data prevista para LocalDate
        LocalDate dataPrevista;
        try {
            dataPrevista = LocalDate.parse(dataPrevistaTexto, formatter);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Data prevista inválida. Use o formato dd/MM/yyyy.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

// Define o status com base na comparação
        LocalDate dataAtual = LocalDate.now();
        String status_Finalizacao = dataAtual.isAfter(dataPrevista) ? "FINALIZADO COM ATRASO" : "FINALIZADO SEM ATRASO"; // SQL para atualizar status e data_devolucao
        String sql = "UPDATE emprestimo "
                + "SET status_emprestimo = ?, data_devolucao = ? "
                + "WHERE id = ?";

        try (Connection conn = Conexao.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, status_Finalizacao); // status definido dinamicamente
            ps.setDate(2, java.sql.Date.valueOf(dataAtual)); // data de devolução = hoje
            ps.setInt(3, idEmprestimo);

            int linhasAfetadas = ps.executeUpdate();

            if (linhasAfetadas > 0) {
                JOptionPane.showMessageDialog(
                        this,
                        "Emprestimo atualizado com sucesso.",
                        "Sucesso",
                        JOptionPane.INFORMATION_MESSAGE
                );
            } else {
                JOptionPane.showMessageDialog(
                        this,
                        "Não foi possível atualizar a 'empre´stimo'. Verifique o ID.",
                        "Atenção",
                        JOptionPane.WARNING_MESSAGE
                );
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro ao atualizar emprestimo: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void atualizarAcervo(int acervoId) {

        String sql = "UPDATE acervo SET status = 'DISPONIVEL' WHERE id = ?";

        try (Connection conn = Conexao.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setInt(1, acervoId);
            ps.executeUpdate();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void carregarEmprestimos() {
        DefaultTableModel model = (DefaultTableModel) tblEmprestimos.getModel();
        model.setRowCount(0); // limpa a tabela

        String sql = "SELECT e.id AS emprestimo_id, "
                + "       a.id AS acervo_id, "
                + "       t.titulo, "
                + "       e.data_emprestimo, "
                + "       e.data_prevista_devolucao, "
                + "       e.status_emprestimo "
                + "FROM emprestimo e "
                + "INNER JOIN acervo a ON e.acervo_id = a.id "
                + "INNER JOIN titulo t ON a.titulo_id = t.id "
                + "WHERE e.usuario_id = ? "
                + "AND e.status_emprestimo = 'EM ANDAMENTO'";

        try (Connection conn = Conexao.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setInt(1, idAluno);

            try (ResultSet rs = ps.executeQuery()) {
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getString("emprestimo_id"),
                        rs.getString("titulo"),
                        sdf.format(rs.getTimestamp("data_emprestimo")),
                        sdf.format(rs.getTimestamp("data_prevista_devolucao")),
                        rs.getString("status_emprestimo"),
                        rs.getInt("acervo_id") // ID do acervo (int) no final
                    });
                }

            }

            //ajustarLarguraColunas();
            //ocultarColunaIdReserva();
            JOptionPane.showMessageDialog(this,
                    "Selecione um Empréstimo de uma obra para efetivar a DEVOLUÇÃO.",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao carregar reservas: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limparSelecao() {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DevolucaoFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEfetivaDevolucao;
    private javax.swing.JButton btnVolta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelDatadevolucao;
    private javax.swing.JTable tblEmprestimos;
    private javax.swing.JTextField txtDataDevolucaoPrevista;
    private javax.swing.JTextField txtDataEmprestimo;
    private javax.swing.JTextField txtIdAcervo;
    private javax.swing.JTextField txtIdAluno;
    private javax.swing.JTextField txtIdEmprestimo;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
