/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.bsi.biblioteca;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Carlos
 */
public class EmprestimoFrame extends javax.swing.JFrame {

    private int idAluno;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EmprestimoFrame.class.getName());

    /**
     * Creates new form EmprestimoDevolucaoFrame
     */
    public EmprestimoFrame() {
        initComponents();
        inicializaCursor();
    }

    private void inicializaCursor() {
        // Garante foco e seleção após a tela estar visível
        SwingUtilities.invokeLater(() -> {
            txtIdAluno.requestFocusInWindow();
            txtIdAluno.selectAll();
            btnEfetivaEmprestimo.setVisible(false);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnVolta = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtIdAluno = new javax.swing.JTextField();
        scrollReserva = new javax.swing.JScrollPane();
        tblReserva = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btnEfetivaEmprestimo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtDataDevolucao = new javax.swing.JTextField();
        txtAutores = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTombo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIdReseva = new javax.swing.JTextField();
        txtIdAcervo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Biblioteca");

        jLabel2.setText("Empréstimo de Livros");

        btnVolta.setText("Volta");
        btnVolta.addActionListener(this::btnVoltaActionPerformed);

        jLabel3.setText("Id do Aluno:");

        txtIdAluno.setColumns(5);
        txtIdAluno.setText(" Informe ID e tecle ENTER");
        txtIdAluno.addActionListener(this::idAlunoPerformed);

        scrollReserva.setBorder(javax.swing.BorderFactory.createTitledBorder("Reservas do Aluno"));

        tblReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Reserva", "Titulo", "Autores", "Data Reserva", "Tombo", "ano", "ID Acervo"
            }
        ));
        tblReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReservaMouseClicked(evt);
            }
        });
        scrollReserva.setViewportView(tblReserva);

        btnEfetivaEmprestimo.setText("Efetivar Empréstimo");
        btnEfetivaEmprestimo.addActionListener(this::btnEfetivaEmprestimoActionPerformed);

        jLabel8.setText("Data da Devolução");

        txtDataDevolucao.setEditable(false);
        txtDataDevolucao.setColumns(10);
        txtDataDevolucao.setText(" ");

        txtAutores.setEditable(false);
        txtAutores.setColumns(25);

        jLabel5.setText("Autores:");

        txtTombo.setEditable(false);
        txtTombo.setColumns(15);
        txtTombo.setText(" ");

        jLabel6.setText("Tombo:");

        txtAno.setEditable(false);
        txtAno.setColumns(5);
        txtAno.setText(" ");

        jLabel7.setText("Ano:");

        txtTitulo.setEditable(false);
        txtTitulo.setColumns(30);
        txtTitulo.setText(" ");

        jLabel4.setText("Título:");

        txtIdReseva.setEditable(false);
        txtIdReseva.setColumns(5);
        txtIdReseva.setText(" ");

        txtIdAcervo.setEditable(false);
        txtIdAcervo.setColumns(5);
        txtIdAcervo.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(258, 258, 258))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(btnEfetivaEmprestimo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIdReseva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(txtIdAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTombo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdReseva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtTombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(btnEfetivaEmprestimo)
                .addGap(34, 34, 34))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(343, 343, 343)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(314, 314, 314)
                                .addComponent(jLabel2)))
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 16, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnVolta)
                .addGap(343, 343, 343))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtIdAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(256, 256, 256))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(scrollReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(btnVolta)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltaActionPerformed
        // Fecha a janela atual
        this.dispose();
        FuncionarioForm telaFuncionrio = new FuncionarioForm();
        telaFuncionrio.setVisible(true);
    }//GEN-LAST:event_btnVoltaActionPerformed

    private void idAlunoPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAlunoPerformed

        String texto = txtIdAluno.getText().trim();

        // Verifica se está vazio
        if (texto.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Informe o ID do aluno.",
                    "Atenção",
                    JOptionPane.WARNING_MESSAGE);
            txtIdAluno.requestFocusInWindow();
            txtIdAluno.selectAll();
            return;
        }

        // Verifica se é numérico
        if (!texto.matches("\\d+")) {
            JOptionPane.showMessageDialog(this,
                    "O ID deve conter apenas números.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
            txtIdAluno.requestFocusInWindow();
            txtIdAluno.selectAll();
            return;
        }

        // Se chegou aqui, é numérico
        idAluno = Integer.parseInt(texto);

        // 👉 Próxima ação
        carregarReservas();

        // Aqui você pode chamar o próximo passo:
        // buscarAluno(idAluno);

    }//GEN-LAST:event_idAlunoPerformed

    private void btnEfetivaEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfetivaEmprestimoActionPerformed

        String tituloLivro = txtTitulo.getText();
        String dataDevolucao = txtDataDevolucao.getText();

        if (tituloLivro.isEmpty() || dataDevolucao.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Não foi possível efetivar o empréstimo. Dados incompletos.",
                    "Atenção",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        inserirEmprestimo();
        //@AQUI
        atualizarReserva();
        atualizarAcervo();
        // Se chegou aqui, é numérico

        String mensagem = String.format(
                "Título \"%s\" emprestado com sucesso.\nAtenção para a data de devolução: %s",
                tituloLivro,
                dataDevolucao
        );

        JOptionPane.showMessageDialog(
                this,
                mensagem,
                "Empréstimo realizado",
                JOptionPane.INFORMATION_MESSAGE
        );
        carregarReservas();
        limparSelecao();
    }//GEN-LAST:event_btnEfetivaEmprestimoActionPerformed
    private void limparSelecao() {
        txtTitulo.setText("");
        txtAutores.setText("");
        txtTombo.setText("");
        txtAno.setText("");
        txtDataDevolucao.setText("");
    }

    private void inserirEmprestimo() {

        String usuarioTexto = txtIdAluno.getText().trim();
        String acervoTexto = txtIdAcervo.getText().trim(); // Vamos assumir que o acervo_id está relacionado à reserva selecionada
        String dataPrevista = txtDataDevolucao.getText().trim();

        // Valida campos
        if (usuarioTexto.isEmpty() || acervoTexto.isEmpty() || dataPrevista.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Não é possível efetivar o empréstimo. Campos obrigatórios estão vazios.",
                    "Atenção",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int usuarioId;
        int acervoId;

        try {
            usuarioId = Integer.parseInt(usuarioTexto);
            acervoId = Integer.parseInt(acervoTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "ID do usuário ou acervo inválido.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        String sql = "INSERT INTO emprestimo "
                + "(usuario_id, acervo_id, data_emprestimo, data_prevista_devolucao, status_emprestimo, data_devolucao) "
                + "VALUES (?, ?, CURRENT_DATE, ?, 'EM ANDAMENTO', NULL)";

        try (Connection conn = Conexao.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setInt(1, usuarioId);
            ps.setInt(2, acervoId);
            ps.setDate(3, java.sql.Date.valueOf(
                    LocalDate.parse(dataPrevista, java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy"))
            ));

            int linhasAfetadas = ps.executeUpdate();

            if (linhasAfetadas > 0) {
                JOptionPane.showMessageDialog(
                        this,
                        "Empréstimo registrado com sucesso.",
                        "Sucesso",
                        JOptionPane.INFORMATION_MESSAGE
                );
            } else {
                JOptionPane.showMessageDialog(
                        this,
                        "Não foi possível registrar o empréstimo.",
                        "Atenção",
                        JOptionPane.WARNING_MESSAGE
                );
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro ao inserir empréstimo: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void atualizarAcervo() {
        String idReservaTexto = txtIdReseva.getText().trim();

        if (idReservaTexto.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Nenhuma reserva selecionada.",
                    "Atenção",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int idReserva;
        try {
            idReserva = Integer.parseInt(idReservaTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "ID da reserva inválido.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // Primeiro, buscar o acervo_id da reserva
        int acervoId = -1;
        String sqlBuscaAcervo = "SELECT acervo_id FROM reserva WHERE id = ?";

        try (Connection conn = Conexao.getConnection(); PreparedStatement psBusca = conn.prepareStatement(sqlBuscaAcervo)) {

            psBusca.setInt(1, idReserva);
            try (ResultSet rs = psBusca.executeQuery()) {
                if (rs.next()) {
                    acervoId = rs.getInt("acervo_id");
                } else {
                    JOptionPane.showMessageDialog(
                            this,
                            "Reserva não encontrada.",
                            "Atenção",
                            JOptionPane.WARNING_MESSAGE
                    );
                    return;
                }
            }

            // Agora, atualizar o status do acervo
            String sqlUpdate = "UPDATE acervo SET status = ? WHERE id = ?";
            try (PreparedStatement psUpdate = conn.prepareStatement(sqlUpdate)) {
                psUpdate.setString(1, "EMPRESTADO");
                psUpdate.setInt(2, acervoId);

                int linhasAfetadas = psUpdate.executeUpdate();
                if (linhasAfetadas > 0) {
                    JOptionPane.showMessageDialog(
                            this,
                            "Status do acervo atualizado para 'EMPRESTADO'.",
                            "Sucesso",
                            JOptionPane.INFORMATION_MESSAGE
                    );
                } else {
                    JOptionPane.showMessageDialog(
                            this,
                            "Não foi possível atualizar o status do acervo.",
                            "Atenção",
                            JOptionPane.WARNING_MESSAGE
                    );
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro ao atualizar acervo: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void atualizarReserva() {
        String idReservaTexto = txtIdReseva.getText().trim();

        // Converte para int
        int idReserva;
        try {
            idReserva = Integer.parseInt(idReservaTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "ID da reserva inválido.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // SQL para atualizar o status da reserva
        String sql = "UPDATE reserva SET status = ? WHERE id = ?";

        try (Connection conn = Conexao.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, "ATENDIDA"); // Novo status
            ps.setInt(2, idReserva);

            int linhasAfetadas = ps.executeUpdate();

            if (linhasAfetadas > 0) {
                JOptionPane.showMessageDialog(
                        this,
                        "Reserva atualizada com sucesso.",
                        "Sucesso",
                        JOptionPane.INFORMATION_MESSAGE
                );
            } else {
                JOptionPane.showMessageDialog(
                        this,
                        "Não foi possível atualizar a reserva. Verifique o ID.",
                        "Atenção",
                        JOptionPane.WARNING_MESSAGE
                );
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro ao atualizar reserva: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void tblReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReservaMouseClicked
        // Se quiser exigir duplo clique, descomente:
        // if (evt.getClickCount() != 2) return;
        int linha = tblReserva.getSelectedRow();

        if (linha == -1) {
            return;
        }

        // Recupera dados da JTable
        txtIdReseva.setText(tblReserva.getValueAt(linha, 0).toString());
        txtTitulo.setText(tblReserva.getValueAt(linha, 1).toString());
        txtAutores.setText(tblReserva.getValueAt(linha, 2).toString());
        txtTombo.setText(tblReserva.getValueAt(linha, 4).toString());
        txtAno.setText(tblReserva.getValueAt(linha, 5).toString());
        txtIdAcervo.setText(tblReserva.getValueAt(linha, 6).toString());

        // Habilita botões
        txtIdAluno.setEnabled(false);
        btnEfetivaEmprestimo.setVisible(true);
        calcularEPreencherDataDevolucao();

    }//GEN-LAST:event_tblReservaMouseClicked
    private void carregarReservas() {
        DefaultTableModel model = (DefaultTableModel) tblReserva.getModel();
        model.setRowCount(0); // limpa a tabela

        String sql = "SELECT "
                + "r.id AS reserva_id, "
                + "t.titulo, "
                + "r.data_reserva, "
                + "ac.tombo, "
                + "t.ano, "
                + "ac.id,"
                + "GROUP_CONCAT(a.nome ORDER BY a.nome SEPARATOR ', ') AS autores "
                + "FROM reserva r "
                + "JOIN acervo ac ON r.acervo_id = ac.id "
                + "JOIN titulo t ON ac.titulo_id = t.id "
                + "LEFT JOIN titulo_autor ta ON t.id = ta.titulo_id "
                + "LEFT JOIN autor a ON a.id = ta.autor_id "
                + "WHERE r.usuario_id = ? "
                + "AND r.status = ? "
                + "GROUP BY "
                + "r.id, t.titulo, r.data_reserva, ac.tombo, t.ano "
                + "ORDER BY r.data_reserva DESC";

        boolean possuiReserva = false;
        scrollReserva.setVisible(true);
        try (Connection conn = Conexao.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setInt(1, idAluno);
            ps.setString(2, "ATIVA");

            try (ResultSet rs = ps.executeQuery()) {
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

                while (rs.next()) {
                    possuiReserva = true;

                    model.addRow(new Object[]{
                        rs.getString("reserva_id"),
                        rs.getString("titulo"),
                        rs.getString("autores"),
                        sdf.format(rs.getTimestamp("data_reserva")),
                        rs.getString("tombo"),
                        rs.getInt("ano"),
                        rs.getInt("id")
                    });
                }

            }

            // Se não encontrou reservas
            if (!possuiReserva) {
                JOptionPane.showMessageDialog(this,
                        "Aluno não possui reserva.",
                        "Informação",
                        JOptionPane.INFORMATION_MESSAGE);

                scrollReserva.setVisible(false);
            } else {
                ajustarLarguraColunas();
                ocultarColunaIdReserva();
                JOptionPane.showMessageDialog(this,
                        "Selecione uma Reserva de uma obra para efetivar o EMPRÉSTIMO.",
                        "Informação",
                        JOptionPane.INFORMATION_MESSAGE);

                scrollReserva.setVisible(true);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao carregar reservas: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void ocultarColunaIdReserva() {
        // Coluna 0 = ID Reserva
        tblReserva.getColumnModel().getColumn(0).setMinWidth(0);
        tblReserva.getColumnModel().getColumn(0).setMaxWidth(0);
        tblReserva.getColumnModel().getColumn(0).setPreferredWidth(0);

        // Coluna 0 = ID Acervo
        tblReserva.getColumnModel().getColumn(6).setMinWidth(0);
        tblReserva.getColumnModel().getColumn(6).setMaxWidth(0);
        tblReserva.getColumnModel().getColumn(6).setPreferredWidth(0);
    }

    private void ajustarLarguraColunas() {
        tblReserva.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

        tblReserva.getColumnModel().getColumn(1).setPreferredWidth(200); // Título
        tblReserva.getColumnModel().getColumn(2).setPreferredWidth(250); // Autores
        tblReserva.getColumnModel().getColumn(3).setPreferredWidth(110); // Data Reserva
        tblReserva.getColumnModel().getColumn(4).setPreferredWidth(100); // Tombo
        tblReserva.getColumnModel().getColumn(5).setPreferredWidth(60);  // Ano
    }

    private void calcularEPreencherDataDevolucao() {
        LocalDate dataBase = LocalDate.now();
        LocalDate dataDevolucao = adicionarDiasUteis(dataBase, 5);

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        txtDataDevolucao.setText(dataDevolucao.format(formatter));
    }

    private LocalDate adicionarDiasUteis(LocalDate dataInicial, int diasUteis) {
        LocalDate data = dataInicial;
        int adicionados = 0;

        while (adicionados < diasUteis) {
            data = data.plusDays(1);

            if (data.getDayOfWeek() != DayOfWeek.SATURDAY
                    && data.getDayOfWeek() != DayOfWeek.SUNDAY) {
                adicionados++;
            }
        }
        return data;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EmprestimoFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEfetivaEmprestimo;
    private javax.swing.JButton btnVolta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane scrollReserva;
    private javax.swing.JTable tblReserva;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtAutores;
    private javax.swing.JTextField txtDataDevolucao;
    private javax.swing.JTextField txtIdAcervo;
    private javax.swing.JTextField txtIdAluno;
    private javax.swing.JTextField txtIdReseva;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTombo;
    // End of variables declaration//GEN-END:variables
}
