/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.bsi.biblioteca;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Carlos
 */
public class FuncionarioForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FuncionarioForm.class.getName());

    /**
     * Creates new form FuncionarioForm
     */
    public FuncionarioForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtnAcervo = new javax.swing.JButton();
        jbtnEmprestimo = new javax.swing.JButton();
        jbtnRelatorios = new javax.swing.JButton();
        jbtnAutores = new javax.swing.JButton();
        jbtnTitulos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jbtnEmprestimo1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Biblioteca BSI");

        jLabel2.setText("Área do Funcioário");

        jbtnAcervo.setText("Cadastro de Acervo");
        jbtnAcervo.addActionListener(this::jbtnAcervoActionPerformed);

        jbtnEmprestimo.setText("Empréstimo");
        jbtnEmprestimo.addActionListener(this::jbtnEmprestimoActionPerformed);

        jbtnRelatorios.setText("Relatórios");
        jbtnRelatorios.addActionListener(this::jbtnRelatoriosActionPerformed);

        jbtnAutores.setText("Autores");
        jbtnAutores.addActionListener(this::jbtnAutoresActionPerformed);

        jbtnTitulos.setText("Títulos");
        jbtnTitulos.addActionListener(this::jbtnTitulosActionPerformed);

        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Sair");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Relacionar Títulos /Autores");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jbtnEmprestimo1.setText("Devolucao");
        jbtnEmprestimo1.addActionListener(this::jbtnEmprestimo1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnTitulos)
                    .addComponent(jbtnAutores)
                    .addComponent(jLabel2))
                .addGap(175, 175, 175))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jbtnAcervo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jbtnEmprestimo1)
                                .addComponent(jbtnEmprestimo))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1)
                                .addComponent(jbtnRelatorios)))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jbtnAutores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnTitulos)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnAcervo)
                .addGap(26, 26, 26)
                .addComponent(jbtnEmprestimo)
                .addGap(18, 18, 18)
                .addComponent(jbtnEmprestimo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnRelatorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRelatoriosActionPerformed
        RelatorioForm telaRelatorio = new RelatorioForm();
        telaRelatorio.setVisible(true);
    }//GEN-LAST:event_jbtnRelatoriosActionPerformed

    private void jbtnAcervoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAcervoActionPerformed
        AcervoForm telaAcervo = new AcervoForm();
        telaAcervo.setVisible(true);
    }//GEN-LAST:event_jbtnAcervoActionPerformed

    private void jbtnTitulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTitulosActionPerformed
        TituloForm telaTitulo = new TituloForm();
        telaTitulo.setVisible(true);
    }//GEN-LAST:event_jbtnTitulosActionPerformed

    private void jbtnAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAutoresActionPerformed
        AutoresForm telaAutores = new AutoresForm();
        telaAutores.setVisible(true);
    }//GEN-LAST:event_jbtnAutoresActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(
                null,
                "Obrigado por usar este sistema!",
                "Mensagem",
                JOptionPane.INFORMATION_MESSAGE
        );
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         TitulosAutorForm telaTituloAutor = new TitulosAutorForm();
        telaTituloAutor.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbtnEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEmprestimoActionPerformed
         EmprestimoFrame telaEmprestimoDevolucao = new EmprestimoFrame();
        telaEmprestimoDevolucao.setVisible(true);
    }//GEN-LAST:event_jbtnEmprestimoActionPerformed

    private void jbtnEmprestimo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEmprestimo1ActionPerformed
        DevolucaoFrame telaDevolucao = new DevolucaoFrame();
        telaDevolucao.setVisible(true);
    }//GEN-LAST:event_jbtnEmprestimo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FuncionarioForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtnAcervo;
    private javax.swing.JButton jbtnAutores;
    private javax.swing.JButton jbtnEmprestimo;
    private javax.swing.JButton jbtnEmprestimo1;
    private javax.swing.JButton jbtnRelatorios;
    private javax.swing.JButton jbtnTitulos;
    // End of variables declaration//GEN-END:variables
}
