/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.bsi.biblioteca;

import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class FuncionarioForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FuncionarioForm.class.getName());

    /**
     * Creates new form FuncionarioForm
     */
    public FuncionarioForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        btnAutores = new javax.swing.JButton();
        btnTitulos = new javax.swing.JButton();
        btnRelacionar = new javax.swing.JButton();
        btnAcervo = new javax.swing.JButton();
        btnEmprestimo = new javax.swing.JButton();
        btnDevolucao = new javax.swing.JButton();
        btnRelatorios = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(900, 500));

        panelHeader.setPreferredSize(new java.awt.Dimension(100, 80));
        panelHeader.setLayout(new java.awt.GridLayout(2, 1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Biblioteca BSI");
        panelHeader.add(jLabel2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Área do Funcionário");
        panelHeader.add(jLabel1);

        getContentPane().add(panelHeader, java.awt.BorderLayout.PAGE_START);

        panelMenu.setBackground(new java.awt.Color(44, 62, 80));
        panelMenu.setPreferredSize(new java.awt.Dimension(500, 350));
        panelMenu.setLayout(new javax.swing.BoxLayout(panelMenu, javax.swing.BoxLayout.Y_AXIS));

        btnAutores.setBackground(new java.awt.Color(52, 73, 94));
        btnAutores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAutores.setForeground(new java.awt.Color(255, 255, 255));
        btnAutores.setText("Autores");
        btnAutores.setAlignmentX(0.5F);
        btnAutores.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15));
        btnAutores.setFocusPainted(false);
        btnAutores.setMaximumSize(new java.awt.Dimension(200, 25));
        btnAutores.addActionListener(this::btnAutoresActionPerformed);
        panelMenu.add(btnAutores);

        btnTitulos.setBackground(new java.awt.Color(52, 73, 94));
        btnTitulos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTitulos.setForeground(new java.awt.Color(255, 255, 255));
        btnTitulos.setText("Títulos");
        btnTitulos.setAlignmentX(0.5F);
        btnTitulos.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15));
        btnTitulos.setFocusPainted(false);
        btnTitulos.setMaximumSize(new java.awt.Dimension(200, 25));
        btnTitulos.addActionListener(this::btnTitulosActionPerformed);
        panelMenu.add(btnTitulos);

        btnRelacionar.setBackground(new java.awt.Color(52, 73, 94));
        btnRelacionar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRelacionar.setForeground(new java.awt.Color(255, 255, 255));
        btnRelacionar.setText("Relacionar Títulos/Autores");
        btnRelacionar.setAlignmentX(0.5F);
        btnRelacionar.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15));
        btnRelacionar.setFocusPainted(false);
        btnRelacionar.setMaximumSize(new java.awt.Dimension(200, 25));
        btnRelacionar.addActionListener(this::btnRelacionarActionPerformed);
        panelMenu.add(btnRelacionar);

        btnAcervo.setBackground(new java.awt.Color(52, 73, 94));
        btnAcervo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAcervo.setForeground(new java.awt.Color(255, 255, 255));
        btnAcervo.setText("Cadastro de Acervo");
        btnAcervo.setAlignmentX(0.5F);
        btnAcervo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15));
        btnAcervo.setFocusPainted(false);
        btnAcervo.setMaximumSize(new java.awt.Dimension(200, 25));
        btnAcervo.addActionListener(this::btnAcervoActionPerformed);
        panelMenu.add(btnAcervo);

        btnEmprestimo.setBackground(new java.awt.Color(52, 73, 94));
        btnEmprestimo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEmprestimo.setForeground(new java.awt.Color(255, 255, 255));
        btnEmprestimo.setText("Empréstimo");
        btnEmprestimo.setAlignmentX(0.5F);
        btnEmprestimo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15));
        btnEmprestimo.setFocusPainted(false);
        btnEmprestimo.setMaximumSize(new java.awt.Dimension(200, 25));
        btnEmprestimo.addActionListener(this::btnEmprestimoActionPerformed);
        panelMenu.add(btnEmprestimo);

        btnDevolucao.setBackground(new java.awt.Color(52, 73, 94));
        btnDevolucao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDevolucao.setForeground(new java.awt.Color(255, 255, 255));
        btnDevolucao.setText("Devolução");
        btnDevolucao.setAlignmentX(0.5F);
        btnDevolucao.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15));
        btnDevolucao.setFocusPainted(false);
        btnDevolucao.setMaximumSize(new java.awt.Dimension(200, 25));
        btnDevolucao.addActionListener(this::btnDevolucaoActionPerformed);
        panelMenu.add(btnDevolucao);

        btnRelatorios.setBackground(new java.awt.Color(52, 73, 94));
        btnRelatorios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRelatorios.setForeground(new java.awt.Color(255, 255, 255));
        btnRelatorios.setText("Relatórios");
        btnRelatorios.setAlignmentX(0.5F);
        btnRelatorios.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15));
        btnRelatorios.setFocusPainted(false);
        btnRelatorios.setMaximumSize(new java.awt.Dimension(200, 25));
        btnRelatorios.addActionListener(this::btnRelatoriosActionPerformed);
        panelMenu.add(btnRelatorios);

        getContentPane().add(panelMenu, java.awt.BorderLayout.LINE_START);

        btnSair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 0, 0));
        btnSair.setText("Sair");
        btnSair.addActionListener(this::btnSairActionPerformed);
        getContentPane().add(btnSair, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(filler1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucaoActionPerformed
         DevolucaoFrame telaDevolucao = new DevolucaoFrame();
        telaDevolucao.setVisible(true);
    }//GEN-LAST:event_btnDevolucaoActionPerformed

    private void btnRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatoriosActionPerformed
       RelatorioForm telaRelatorio = new RelatorioForm();
        telaRelatorio.setVisible(true);
    }//GEN-LAST:event_btnRelatoriosActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
         JOptionPane.showMessageDialog(
                null,
                "Obrigado por usar este sistema!",
                "Mensagem",
                JOptionPane.INFORMATION_MESSAGE
        );
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoresActionPerformed
        RelatorioForm telaRelatorio = new RelatorioForm();
        telaRelatorio.setVisible(true);
    }//GEN-LAST:event_btnAutoresActionPerformed

    private void btnTitulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitulosActionPerformed
        TituloForm telaTitulo = new TituloForm();
        telaTitulo.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnTitulosActionPerformed

    private void btnRelacionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelacionarActionPerformed
        AcervoForm telaAcervo = new AcervoForm();
        telaAcervo.setVisible(true);
    }//GEN-LAST:event_btnRelacionarActionPerformed

    private void btnAcervoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcervoActionPerformed
         AcervoForm telaAcervo = new AcervoForm();
        telaAcervo.setVisible(true);
    }//GEN-LAST:event_btnAcervoActionPerformed

    private void btnEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestimoActionPerformed
         EmprestimoFrame telaEmprestimoDevolucao = new EmprestimoFrame();
        telaEmprestimoDevolucao.setVisible(true);
    }//GEN-LAST:event_btnEmprestimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FuncionarioForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcervo;
    private javax.swing.JButton btnAutores;
    private javax.swing.JButton btnDevolucao;
    private javax.swing.JButton btnEmprestimo;
    private javax.swing.JButton btnRelacionar;
    private javax.swing.JButton btnRelatorios;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnTitulos;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
