/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.bsi.biblioteca;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos
 */
public class TitulosAutorForm extends javax.swing.JFrame {

    private int idAutorSelecionado = -1;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TitulosAutorForm.class.getName());

    /**
     * Creates new form TitulosAutorForm
     */
    public TitulosAutorForm() {
        initComponents();
        ajustarColunasAutores(); // ← AQUI É O PONTO CERTO
        carregarTitulos();
    }

    private void ajustarColunasAutores() {
        // tblAutores.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

        tblAutores.getColumnModel().getColumn(0).setPreferredWidth(60);  // ID
        tblAutores.getColumnModel().getColumn(1).setPreferredWidth(500); // Nome do Autor
    }

    private void carregarTitulos() {
        btnAdicionarAutor.setEnabled(false);
        btnRemoverAutor.setEnabled(false);
        DefaultTableModel model
                = (DefaultTableModel) tblTitulos.getModel();

        model.setRowCount(0); // limpa a tabela
        ajustarColunasTitulos();
        try {
            Connection conn = Conexao.getConnection();

            String sql
                    = "SELECT id, titulo,  editora "
                    + "FROM titulo "
                    + "ORDER BY editora ASC, titulo ASC ";

            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("titulo"),
                    rs.getString("editora")
                });
            }

            rs.close();
            ps.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao carregar Títulos: " + e.getMessage());
        }
    }

    private void carregarAutoresDasObras(int idTitulo) {

        DefaultTableModel model
                = (DefaultTableModel) tblAutores.getModel();

        model.setRowCount(0); // limpa a tabela

        try {
            Connection conn = Conexao.getConnection();

            String sql
                    = "SELECT a.id, a.nome "
                    + "FROM autor a "
                    + "JOIN titulo_autor ta ON ta.autor_id = a.id "
                    + "WHERE ta.titulo_id = ? "
                    + "ORDER BY a.nome";

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, idTitulo); // parâmetro do título

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("nome")
                });
            }

            rs.close();
            ps.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao carregar autores da obra: " + e.getMessage());
        }
    }

    private void ajustarColunasTitulos() {
        // tblAutores.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

        tblTitulos.getColumnModel().getColumn(0).setPreferredWidth(60);  // ID
        tblTitulos.getColumnModel().getColumn(1).setPreferredWidth(300); // Nome do Autor
        tblTitulos.getColumnModel().getColumn(2).setPreferredWidth(200); // Nome do Autor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        frmTitulo = new javax.swing.JScrollPane();
        tblTitulos = new javax.swing.JTable();
        btnVolta = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdTitulo = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtEditora = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAutores = new javax.swing.JTable();
        btnAdicionarAutor = new javax.swing.JButton();
        btnRemoverAutor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Biblioteca BSI");

        jLabel2.setText("Área do Funcioário");

        jLabel3.setText("Relacionar Título / Autor");

        tblTitulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Título", "Editora"
            }
        ));
        tblTitulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTituloMouseClicked(evt);
            }
        });
        frmTitulo.setViewportView(tblTitulos);

        btnVolta.setText("Volta");
        btnVolta.addActionListener(this::btnVoltaActionPerformed);

        jLabel4.setText("ID");

        jLabel5.setText("Título");

        jLabel6.setText("Editora");

        txtIdTitulo.setColumns(5);

        txtTitulo.setColumns(20);

        txtEditora.setColumns(15);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Autores da Obra", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        tblAutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nome do Autor"
            }
        ));
        tblAutores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAutoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAutores);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnAdicionarAutor.setText("Adicionar Autor");
        btnAdicionarAutor.addActionListener(this::btnAdicionarAutorActionPerformed);

        btnRemoverAutor.setText("Remover Autor");
        btnRemoverAutor.addActionListener(this::btnRemoverAutorActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(frmTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtIdTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtEditora))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel4)
                .addGap(87, 87, 87)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolta)
                .addGap(260, 260, 260))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(btnAdicionarAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRemoverAutor)
                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarAutor)
                    .addComponent(btnRemoverAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(frmTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(btnVolta)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltaActionPerformed
        // Fecha a janela atual
        this.dispose();
        FuncionarioForm telaFuncionrio = new FuncionarioForm();
        telaFuncionrio.setVisible(true);
    }//GEN-LAST:event_btnVoltaActionPerformed

    private void tblTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTituloMouseClicked
        // Se quiser exigir duplo clique, descomente:
        // if (evt.getClickCount() != 2) return;
        int linha = tblTitulos.getSelectedRow();

        if (linha == -1) {
            return;
        }

        // Recupera dados da JTable
        txtIdTitulo.setText(tblTitulos.getValueAt(linha, 0).toString());
        txtTitulo.setText(tblTitulos.getValueAt(linha, 1).toString());
        txtEditora.setText(tblTitulos.getValueAt(linha, 2).toString());

        // Recupera o ID do título selecionado
        int idTitulo = Integer.parseInt(
                tblTitulos.getValueAt(linha, 0).toString()
        );
        carregarAutoresDasObras(idTitulo);
        //tblAutores.getColumn(0).setPreferredWidth(15);
        //tblAutores.getColumn(1).setPreferredWidth(50);
        // Habilita botões
        btnAdicionarAutor.setEnabled(true);
        btnRemoverAutor.setEnabled(false);
        //btnExcluir.setEnabled(true);
    }//GEN-LAST:event_tblTituloMouseClicked

    private void btnAdicionarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarAutorActionPerformed

        // Verifica se há título selecionado
        if (txtIdTitulo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Selecione um título primeiro.");
            return;
        }

        int idTitulo = Integer.parseInt(txtIdTitulo.getText());

        // Cria ComboBox dinamicamente
        javax.swing.JComboBox<AutorItem> comboAutores
                = criarComboAutoresNaoAssociados(idTitulo);

        int opcao = JOptionPane.showConfirmDialog(
                this,
                comboAutores,
                "Selecione um autor",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (opcao == JOptionPane.OK_OPTION) {

            AutorItem autorSelecionado
                    = (AutorItem) comboAutores.getSelectedItem();

            if (autorSelecionado != null) {

                // Insere no banco
                adicionarAutorAoTitulo(idTitulo, autorSelecionado.getId());

                // Atualiza a tabela de autores
                carregarAutoresDasObras(idTitulo);
            }
        }


    }//GEN-LAST:event_btnAdicionarAutorActionPerformed

    private void btnRemoverAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverAutorActionPerformed

        if (idAutorSelecionado == -1 || txtIdTitulo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Selecione um autor para remover.");
            return;
        }

        int idTitulo = Integer.parseInt(txtIdTitulo.getText());

        int confirmacao = JOptionPane.showConfirmDialog(
                this,
                "Deseja remover este autor da obra?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION
        );

        if (confirmacao == JOptionPane.YES_OPTION) {

            removerAutorDoTitulo(idTitulo, idAutorSelecionado);

            // Atualiza tabela
            carregarAutoresDasObras(idTitulo);

            // Reseta seleção
            idAutorSelecionado = -1;
            btnRemoverAutor.setEnabled(false);
        }


    }//GEN-LAST:event_btnRemoverAutorActionPerformed
    private void removerAutorDoTitulo(int idTitulo, int idAutor) {

        try {
            Connection conn = Conexao.getConnection();

            String sql
                    = "DELETE FROM titulo_autor "
                    + "WHERE titulo_id = ? AND autor_id = ?";

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, idTitulo);
            ps.setInt(2, idAutor);

            ps.executeUpdate();

            ps.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao remover autor: " + e.getMessage());
        }
    }

    private void tblAutoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAutoresMouseClicked
        btnAdicionarAutor.setEnabled(false);
        btnRemoverAutor.setEnabled(true);

        int linha = tblAutores.getSelectedRow();

        if (linha == -1) {
            idAutorSelecionado = -1;
            return;
        }

        // Coluna 0 = ID do Autor
        idAutorSelecionado = Integer.parseInt(
                tblAutores.getValueAt(linha, 0).toString()
        );


    }//GEN-LAST:event_tblAutoresMouseClicked
    private javax.swing.JComboBox<AutorItem> criarComboAutoresNaoAssociados(int idTitulo) {

        javax.swing.JComboBox<AutorItem> combo = new javax.swing.JComboBox<>();

        try {
            Connection conn = Conexao.getConnection();

            String sql
                    = "SELECT id, nome "
                    + "FROM autor "
                    + "WHERE id NOT IN ( "
                    + "    SELECT autor_id "
                    + "    FROM titulo_autor "
                    + "    WHERE titulo_id = ? "
                    + ") "
                    + "ORDER BY nome";

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, idTitulo);

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                combo.addItem(new AutorItem(
                        rs.getInt("id"),
                        rs.getString("nome")
                ));
            }

            rs.close();
            ps.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao carregar autores disponíveis: " + e.getMessage());
        }

        return combo;
    }

    private void adicionarAutorAoTitulo(int idTitulo, int idAutor) {

        try {
            Connection conn = Conexao.getConnection();

            String sql
                    = "INSERT INTO titulo_autor (titulo_id, autor_id) VALUES (?, ?)";

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, idTitulo);
            ps.setInt(2, idAutor);

            ps.executeUpdate();

            ps.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao adicionar autor: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TitulosAutorForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarAutor;
    private javax.swing.JButton btnRemoverAutor;
    private javax.swing.JButton btnVolta;
    private javax.swing.JScrollPane frmTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAutores;
    private javax.swing.JTable tblTitulos;
    private javax.swing.JTextField txtEditora;
    private javax.swing.JTextField txtIdTitulo;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
