/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.bsi.biblioteca;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos
 */
public class TituloForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TituloForm.class.getName());

    /**
     * Creates new form TituloForm
     */
    public TituloForm() {
        initComponents();
        btnIncluir.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        carregarTitulos();
    }

    private void carregarTitulos() {

        DefaultTableModel model
                = (DefaultTableModel) tblTitulos.getModel();

        model.setRowCount(0); // limpa a tabela

        try {
            Connection conn = Conexao.getConnection();

            String sql
                    = "SELECT id, titulo, isbn, ano, editora "
                    + "FROM titulo "
                    + "ORDER BY editora ASC, titulo ASC ";

            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("titulo"),
                    rs.getString("isbn"),
                    rs.getString("ano"),
                    rs.getString("editora")
                });
            }

            rs.close();
            ps.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao carregar Títulos: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdTitulo = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtISBN = new javax.swing.JTextField();
        txtAnoTitulo = new javax.swing.JTextField();
        cblEditora = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTitulos = new javax.swing.JTable();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnVolta = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Biblioteca BSI");

        jLabel2.setText("Cadastro de Títulos");

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        jLabel3.setText("id: ");

        jLabel4.setText("Título");

        jLabel5.setText("ISBN");

        jLabel6.setText("Ano");

        jLabel7.setText("Editora");

        txtIdTitulo.setEditable(false);
        txtIdTitulo.setColumns(5);

        txtTitulo.setColumns(30);

        txtISBN.setColumns(10);

        txtAnoTitulo.setColumns(5);

        cblEditora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------------", "Novatec Editora", "Editora Pearson", "Editora LTC (Livros Técnicos e Científicos) ", "Editora Atlas", "Editora Érica", "Editora Bookman", "Editora McGraw-Hill", "Editora Springer" }));

        tblTitulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Título", "ISBN", "Ano", "Editora"
            }
        ));
        tblTitulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTituloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTitulos);

        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(this::btnIncluirActionPerformed);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(this::btnAlterarActionPerformed);

        btnVolta.setText("Volta");
        btnVolta.addActionListener(this::btnVoltaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 104, Short.MAX_VALUE)
                .addComponent(btnIncluir)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtAnoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnAlterar)
                                            .addComponent(cblEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(90, 90, 90))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpar)
                        .addGap(79, 79, 79))))
            .addGroup(layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(btnVolta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAnoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cblEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnLimpar)
                    .addComponent(btnIncluir)
                    .addComponent(btnAlterar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnVolta)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparTela();
        btnIncluir.setEnabled(true);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        if (!validarCamposObrigatorios()) {
            return;
        }
        try {
            Connection conn = Conexao.getConnection();

            String sql
                    = "INSERT INTO titulo ( titulo, isbn, ano, editora) "
                    + "VALUES (?, ?, ?, ?)";

            PreparedStatement ps = conn.prepareStatement(sql);

            // Status vindo do ButtonGroup
            String status = "";

            ps.setString(1, txtTitulo.getText());
            ps.setString(2, txtISBN.getText());
            ps.setString(3, txtAnoTitulo.getText());
            ps.setString(4, cblEditora.getSelectedItem().toString());

            ps.executeUpdate();

            ps.close();
            conn.close();

            JOptionPane.showMessageDialog(this,
                    "Título incluído com sucesso!!!");
            limparTela();
            carregarTitulos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao incluir: " + e.getMessage());
        }

    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // 1️⃣ Validação: precisa ter ID
        if (txtIdTitulo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Selecione um Título na lista para alterar.");
            return;
        }
        if (!validarCamposObrigatorios()) {
            return;
        }
        try {
            Connection conn = Conexao.getConnection();

            String sql
                    = "UPDATE titulo "
                    + "SET titulo = ?, isbn = ?, ano = ?, editora = ? "
                    + "WHERE id = ?";

            PreparedStatement ps = conn.prepareStatement(sql);

            // 2️⃣ Status via RadioButton
            ps.setString(1, txtTitulo.getText());
            ps.setString(2, txtISBN.getText());
            ps.setString(3, txtAnoTitulo.getText());
            ps.setString(4, cblEditora.getSelectedItem().toString());
            ps.setInt(5, Integer.parseInt(txtIdTitulo.getText()));

            ps.executeUpdate();

            ps.close();
            conn.close();

            // 3️⃣ Feedback ao usuário
            JOptionPane.showMessageDialog(this,
                    "Título alterado com sucesso!");

            // 4️⃣ Limpa e recarrega
            limparTela();
            carregarTitulos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao alterar Título: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        int idSelecionado = Integer.parseInt(txtIdTitulo.getText());

        // Desabilita botões durante a confirmação
        btnIncluir.setEnabled(false);
        btnAlterar.setEnabled(false);

        int opcao = JOptionPane.showConfirmDialog(
                this,
                "Confirma a exclusão do Título selecionado?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        // Se cancelar
        if (opcao != JOptionPane.YES_OPTION) {
            btnIncluir.setEnabled(true);
            btnAlterar.setEnabled(true);
            return;
        }

        try {
            Connection conn = Conexao.getConnection();

            String sql = "DELETE FROM titulo WHERE id = ?";

            PreparedStatement ps = conn.prepareStatement(sql);

            ps.setInt(1, Integer.parseInt(txtIdTitulo.getText()));

            ps.executeUpdate();

            ps.close();
            conn.close();

            JOptionPane.showMessageDialog(this,
                    "Título excluído com sucesso!");

            // Volta para tela inicial
            limparTela();
            carregarTitulos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao excluir Título: " + e.getMessage());
        }


    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tblTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTituloMouseClicked
        // Se quiser exigir duplo clique, descomente:
        // if (evt.getClickCount() != 2) return;
        int linha = tblTitulos.getSelectedRow();

        if (linha == -1) {
            return;
        }

        // Recupera dados da JTable
        txtIdTitulo.setText(tblTitulos.getValueAt(linha, 0).toString());
        txtTitulo.setText(tblTitulos.getValueAt(linha, 1).toString());
        txtISBN.setText(tblTitulos.getValueAt(linha, 2).toString());
        txtAnoTitulo.setText(tblTitulos.getValueAt(linha, 3).toString());
        String editora = tblTitulos.getValueAt(linha, 4).toString();
        cblEditora.setSelectedItem(editora);

        // Habilita botões
        btnIncluir.setEnabled(false);
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);
    }//GEN-LAST:event_tblTituloMouseClicked

    private void btnVoltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltaActionPerformed
        // Fecha a janela atual
        this.dispose();
        FuncionarioForm telaFuncionrio = new FuncionarioForm();
        telaFuncionrio.setVisible(true);
    }//GEN-LAST:event_btnVoltaActionPerformed
    private void limparTela() {

        // Campos de texto
        if (txtIdTitulo != null) {
            txtIdTitulo.setText("");
        }
        if (txtTitulo != null) {
            txtTitulo.setText("");
        }
        if (txtISBN != null) {
            txtISBN.setText("");
        }

        if (txtAnoTitulo != null) {
            txtAnoTitulo.setText("");
        }

        if (cblEditora != null) {
            cblEditora.setSelectedIndex(0);
        }
        btnIncluir.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TituloForm().setVisible(true));
    }

    private boolean validarCamposObrigatorios() {

        // Titulo do livro
        if (txtTitulo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Informe Título do Livro!");
            txtTitulo.requestFocus();
            return false;
        }

        // ISBN
        if (txtISBN.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Informe ISBN do Livro!");
            txtISBN.requestFocus();
            return false;
        }
        // Ano do Livro
        if (txtAnoTitulo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Informe Ano do Livro!");
            txtAnoTitulo.requestFocus();
            return false;
        }
// Editora (JComboBox)
        String editoraSelecionado = cblEditora.getSelectedItem().toString();
        if (editoraSelecionado.equals("-----------------")) {
            JOptionPane.showMessageDialog(this,
                    "Selecione a Editora!");
            cblEditora.requestFocus();
            return false;
        }

        return true; // tudo OK
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVolta;
    private javax.swing.JComboBox<String> cblEditora;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTitulos;
    private javax.swing.JTextField txtAnoTitulo;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtIdTitulo;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
