/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.bsi.biblioteca;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTextField;
import javax.swing.JComboBox;

/**
 *
 * @author Carlos
 */
public class UsuarioForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UsuarioForm.class.getName());

    /**
     * Creates new form UsuarioForm
     */
    public UsuarioForm() {
        initComponents();
        btnIncluir.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        carregarUsuarios();
        java.awt.EventQueue.invokeLater(() -> {
            txtNome.requestFocusInWindow();
        });

        // Adiciona os RadioButtons existentes ao grupo que podemos manipular
        // Inicializa o atributo da classe
        // Adiciona os RadioButtons que já existem
    }

    private void carregarUsuarios() {

        DefaultTableModel model
                = (DefaultTableModel) tblUsuarios.getModel();

        model.setRowCount(0); // limpa a tabela

        try {
            Connection conn = Conexao.getConnection();

            String sql
                    = "SELECT id, nome, tipo, status "
                    + "FROM usuario "
                    + "ORDER BY tipo ASC, nome ASC";

            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("nome"),
                    rs.getString("tipo"),
                    rs.getString("status")
                });
            }

            rs.close();
            ps.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao carregar usuários: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoStatus = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        nome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcbTipo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        rbnAtivo = new javax.swing.JRadioButton();
        rbnInadimplente = new javax.swing.JRadioButton();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnLimpar = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cadastro de Usuario");

        jLabel2.setText("ID:");

        txtId.setEditable(false);
        txtId.setColumns(5);

        nome.setText("Nome:");

        txtNome.setColumns(20);

        jLabel3.setText("Senha");

        jLabel4.setText("Tipo:");

        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "ALUNO", "ADMIN", "FUNCIONARIO" }));

        jLabel5.setText("Status");

        grupoStatus.add(rbnAtivo);
        rbnAtivo.setText("Ativo");

        grupoStatus.add(rbnInadimplente);
        rbnInadimplente.setText("Inadiplente");

        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(this::btnIncluirActionPerformed);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(this::btnAlterarActionPerformed);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Tipo", "Status"
            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblUsuarios);

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        txtSenha.setColumns(10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbnInadimplente)
                                    .addComponent(rbnAtivo)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnIncluir)
                        .addGap(39, 39, 39)
                        .addComponent(btnAlterar)
                        .addGap(32, 32, 32)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar)))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbnAtivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbnInadimplente)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnLimpar))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        if (!validarCamposObrigatorios()) {
            return;
        }
        try {
            Connection conn = Conexao.getConnection();

            String sql
                    = "INSERT INTO usuario ( nome, senha, tipo, status) "
                    + "VALUES (?, ?, ?, ?)";

            PreparedStatement ps = conn.prepareStatement(sql);

            // Status vindo do ButtonGroup
            String status = "";

            if (rbnAtivo.isSelected()) {
                status = "ATIVO";
            } else if (rbnInadimplente.isSelected()) {
                status = "INADIMPLENTE";
            }
            ps.setString(1, txtNome.getText());
            ps.setString(2, new String(txtSenha.getPassword()));
            ps.setString(3, jcbTipo.getSelectedItem().toString());
            ps.setString(4, status);

            ps.executeUpdate();

            ps.close();
            conn.close();

            JOptionPane.showMessageDialog(this,
                    "Usuário incluído com sucesso!");
            limparTela();
            carregarUsuarios();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao incluir: " + e.getMessage());
        }

    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparTela();
        btnIncluir.setEnabled(true);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

        // 1️⃣ Validação: precisa ter ID
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Selecione um usuário na lista para alterar.");
            return;
        }
        if (!validarCamposObrigatorios()) {
            return;
        }
        try {
            Connection conn = Conexao.getConnection();

            String sql
                    = "UPDATE usuario "
                    + "SET nome = ?, senha = ?, tipo = ?, status = ? "
                    + "WHERE id = ?";

            PreparedStatement ps = conn.prepareStatement(sql);

            // 2️⃣ Status via RadioButton
            String status;
            if (rbnAtivo.isSelected()) {
                status = "ATIVO";
            } else if (rbnInadimplente.isSelected()) {
                status = "INADIMPLENTE";
            } else {
                JOptionPane.showMessageDialog(this,
                        "Selecione o status!");
                return;
            }

            ps.setString(1, txtNome.getText());
            ps.setString(2, txtSenha.getText());
            ps.setString(3, jcbTipo.getSelectedItem().toString());
            ps.setString(4, status);
            ps.setInt(5, Integer.parseInt(txtId.getText()));

            ps.executeUpdate();

            ps.close();
            conn.close();

            // 3️⃣ Feedback ao usuário
            JOptionPane.showMessageDialog(this,
                    "Usuário alterado com sucesso!");

            // 4️⃣ Limpa e recarrega
            limparTela();
            carregarUsuarios();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao alterar usuário: " + e.getMessage());
        }

    }//GEN-LAST:event_btnAlterarActionPerformed
    private boolean validarCamposObrigatorios() {

        // Nome
        if (txtNome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Informe o nome do usuário!");
            txtNome.requestFocus();
            return false;
        }

        // Senha (JPasswordField)
        if (txtSenha.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this,
                    "Informe a senha!");
            txtSenha.requestFocus();
            return false;
        }
// Tipo (JComboBox)
        String tipoSelecionado = jcbTipo.getSelectedItem().toString();
        if (tipoSelecionado.equals("--------")) {
            JOptionPane.showMessageDialog(this,
                    "Selecione o tipo do usuário!");
            jcbTipo.requestFocus();
            return false;
        }
        // Status (ButtonGroup)
        if (grupoStatus.getSelection() == null) {
            JOptionPane.showMessageDialog(this,
                    "Selecione o status do usuário!");
            rbnAtivo.requestFocus(); // ou rbnInadimplente
            return false;
        }
        return true; // tudo OK
    }

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
//JOptionPane.showMessageDialog(this, "Clique detectado!");

        // Se quiser exigir duplo clique, descomente:
        // if (evt.getClickCount() != 2) return;
        int linha = tblUsuarios.getSelectedRow();

        if (linha == -1) {
            return;
        }

        // Recupera dados da JTable
        txtId.setText(tblUsuarios.getValueAt(linha, 0).toString());
        txtNome.setText(tblUsuarios.getValueAt(linha, 1).toString());

        String tipo = tblUsuarios.getValueAt(linha, 2).toString();
        jcbTipo.setSelectedItem(tipo);

        String status = tblUsuarios.getValueAt(linha, 3).toString();

        // RadioButtons de status
        if (status.equalsIgnoreCase("ATIVO")) {
            rbnAtivo.setSelected(true);
        } else {
            rbnInadimplente.setSelected(true);
        }

        // Habilita botões
        btnIncluir.setEnabled(false);
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);

    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        int idSelecionado = Integer.parseInt(txtId.getText());

        // Impede auto-exclusão
        if (idSelecionado == SessaoUsuario.idUsuarioLogado) {
            JOptionPane.showMessageDialog(this,
                    "Você não pode excluir o seu próprio usuário!");
            return;
        }

        // Desabilita botões durante a confirmação
        btnIncluir.setEnabled(false);
        btnAlterar.setEnabled(false);

        int opcao = JOptionPane.showConfirmDialog(
                this,
                "Confirma a exclusão do usuário selecionado?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        // Se cancelar
        if (opcao != JOptionPane.YES_OPTION) {
            btnIncluir.setEnabled(true);
            btnAlterar.setEnabled(true);
            return;
        }

        try {
            Connection conn = Conexao.getConnection();

            String sql = "DELETE FROM usuario WHERE id = ?";

            PreparedStatement ps = conn.prepareStatement(sql);

            ps.setInt(1, Integer.parseInt(txtId.getText()));

            ps.executeUpdate();

            ps.close();
            conn.close();

            JOptionPane.showMessageDialog(this,
                    "Usuário excluído com sucesso!");

            // Volta para tela inicial
            limparTela();
            carregarUsuarios();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao excluir usuário: " + e.getMessage());
        }


    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    private void limparTela() {

        // Campos de texto
        if (txtId != null) {
            txtId.setText("");
        }
        if (txtNome != null) {
            txtNome.setText("");
        }
        if (txtSenha != null) {
            txtSenha.setText("");
        }

        if (jcbTipo != null) {
            jcbTipo.setSelectedIndex(0);
        }

        if (rbnAtivo != null) {
            rbnAtivo.setSelected(false);
        }
        if (rbnInadimplente != null) {
            rbnInadimplente.setSelected(false);
        }

        if (tblUsuarios != null) {
            tblUsuarios.clearSelection();
        }

        if (txtNome != null) {
            txtNome.requestFocus();
        }
        btnIncluir.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UsuarioForm().setVisible(true));
    }

    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JComboBox<String> cbStatus;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.ButtonGroup grupoStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> jcbTipo;
    private javax.swing.JLabel nome;
    private javax.swing.JRadioButton rbnAtivo;
    private javax.swing.JRadioButton rbnInadimplente;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
